### ISSUE TITLE
Any plans to update this for 0.8?

### ISSUE THREAD

**Issue by LiveLaden** [kree-nickm/fvtt-cursor-popups#1]
It works on 0.8, but with some minor glitches, the cursor popups never go away after you press it once

**Comment by kree-nickm** [comment]
Once I start using 0.8 I will make sure this works with it. At the moment I am taking a break from running games and haven't done anything with modules.

**Comment by LiveLaden** [comment]
Someone made this fork that works already on 0.8, you can prob talk to the person to make it official
Love the module

https://github.com/CowWhispered/fvtt-cursor-popups

**Comment by kree-nickm** [comment]
Finally updated it myself.
